### ISSUE TITLE
cant prestart master pump

### ISSUE THREAD

**Issue by docsparks** [OpenSprinkler/OpenSprinkler-Firmware#107]
when trying to offset timing for pump delay, to start you can  (+) time to make the pump start a few seconds after a zone opens, for pump stop you can (-) time to have it stop before zones close.   I cannot (-) the time of the pump start to get my pump to turn on three seconds prior to running any zones.    In the past this worked, figured it was an app glitch but updates havent fixed it. thank you

**Comment by rayshobby** [comment]
No, this is not an app glitch, this is due to the way pump start is implemented since a few firmware versions ago -- pump is dynamically scheduled based on the current station queue. Since a station can be added to the queue at any time, there is no easy way for the algorithm to predict when a station is added, so it cannot possibly start pump before a station starts. Allowing a pump to start some time before a zone starts would require pretty significant change to the implementation of the scheduler. At the moment, there is one work-around, that is, set your first non-master zone (for example, if you use zone 1 as master, then zone 2 is the first non-master zone) as a dummy zone, and put it in a program with a few seconds of run time. This way, that dummy zone will always run first, activating the master zone, this achieves the effect of starting master a few seconds before any other zone starts. I am closing this issue for now because resolving it is going to incur some fundamental changes to the algorithm. We can plan for that but it's unlikely to be any time soon. Thanks.
