### ISSUE TITLE
Allow for specification of configuration sets

### ISSUE THREAD

**Issue by andrewnicols** [OpenSprinkler/OpenSprinkler-Firmware#121]
It would be really helpful to have some kind of ability to choose between different configuration sets - particularly because as the time of year changes the reticulation requirements change.

For example, Winter you may want entirely off (manual control only for example)
Going into Autumn you may want to have some stations enabled, others disabled, and only short times.
Going into Summer you may want more stations, and more time, multiple times per day,
And then into Spring you want to start to back them off.

Right now my solution is to download the configuration and restore. Having some kind of ability to choose from time sets would be handy.

**Comment by rayshobby** [comment]
Thanks for the suggestion. This is certainly doable on OSPi, but I would hesitate to implement this for OS 3.x because of the limited storage. I think at the moment the best option is probably to manually save a few copies of different configuration sets and manually import them as needed. It's also possible to write an external script to automate this if needed, based on the time of the year.
