### ISSUE TITLE
Station notes not backed up to file

### ISSUE THREAD

**Issue by KeithoHimself** [OpenSprinkler/OpenSprinkler-Firmware#152]
Text entered in the "Station Notes:" field for each station is not backed up when Export Configuration -> to File is selected.  An inspection of the JSON backup file shows no notes.

Steps to reproduce:
1. enter station notes
2. backup to file
3. remove station notes
4. restore from backup file

Station notes have not been restored

**Comment by rayshobby** [comment]
Station notes are a cloud-synced feature, it is not stored in the controller itself. Just like station images, this requires logging into opensprinkler.com from the web interface or app, and it's synced on the cloud server. The reason it's done this way is that station notes and images are fairly large and not suitable to be stored on the controller due to the relatively small flash memory size.
