### ISSUE TITLE
Development on Scheduler UI Branch

### ISSUE THREAD

**Issue by trbolexis** [OpenSprinkler/OpenSprinkler-Firmware#182]
Is this branch of Opensprinkler with the group scheduling feature functional? Is it actively being developed?

I am planning to continue development, and need an idea if this will be a useful place from which to start my work.

**Comment by rianadon** [comment]
If you do mean the `scheduler-feature` branch, I've built on it in #173 which would be a good place to continue from.

**Comment by rayshobby** [comment]
Most of the changes in the scheduler-features branch are now merged into firmware 2.2.0 source code:
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/tree/dev/os220
I am currently testing and fixing bugs if I find any. The scheduler UI branch will also be gradually merged. I am closing this ticket now since it's being actively developed. Once it's released, if there are any issues you can re-open the ticket.
