### ISSUE TITLE
Station 8 not working properly with PCA9555 / help to invert

### ISSUE THREAD

**Issue by PipeDeveloper** [OpenSprinkler/OpenSprinkler-Firmware#189]
Hello.

I have builded a custom board with PCA9555
With the original firmware .bin file there is no issues.

With the custom firmware compiled on platformIO (by downloading the master repository and without touching anything on the code). It doesnt change the state only for station 8.
PCA9555 is high as default, so when you trigger it it changes to low (except the station8).

Also i would like to ask to help to invert the trigger, so low as default, high to trigger.

I have followed this thread:
https://opensprinkler.com/forums/topic/os-3-0-lan-adapter/#post-71094

i have edited this line on `opensprinkler.cpp` file. (actual line on this date 1120)

```
reg = (reg&0xFF00) | station_bits[0];
```
to

```
reg = (reg&0xFF00) | ~station_bits[0];
```
I have recompiled and this happen:
The default status is now low, but when i trigger an station nothing happen.

There is something rare here...
on the modified firmware station 8 is the only that it goes to high when trigger, but after finish the time, it continues high (the spected is to it goes to low), then after waiting around 12 minutes, it goes to low (i have set 5seconds to test it)

**Comment by rayshobby** [comment]
This isn't an issue I am aware of. One possibility is that when you compiled with platformio, it's probably using ESP8266 core 3.0.2 by default. This is problematic because the current firmware as is does not work with core 3.0.2. You will need to specific platformio to use ESP8266 core 2.7.4.

The next firmware (2.2.0) will be compiled using core 3.0.2.
