### ISSUE TITLE
Please add a pause feature

### ISSUE THREAD

**Issue by KlausHans** [OpenSprinkler/OpenSprinkler-Firmware#208]
I would love to have a pause feature in Opensprinkler. That means all current programs will be set on hold until the unpause command is set or a configurable timeout is reached. In the last case it should be configurable if the programs continue or if they should be stopped completely.

My use case is to only irrigate if enough power comes from my pv plant. If the pv power is to low i want to pause the programs and if enough sun is back it should continue. My pump takes over 800 W, so this feature is quite significant for me.
Another use case could be to pause the irrigation to use the well water for something else.

**Comment by rayshobby** [comment]
The pause feature is available in the scheduler-features branch:
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/tree/scheduler-feature
I am starting to slowly integrate the changes in that branch into the upcoming firmware 2.2.0. Will probably integrate the changes one step at a time because it involves both firmware and also UI changes.
