### ISSUE TITLE
log size

### ISSUE THREAD

**Issue by garudaonekh** [OpenSprinkler/OpenSprinkler-Firmware#224]
Hi, 
I use esp32 4MB flash. The sketch size is 1.25MB.
How much data log can it store based on this? approximately, how long? I also need to allocate for OTA partition as well.

Through my observation,  it looks like it consume around 800Bytes per day if around 20 records.

Thanks

**Comment by rayshobby** [comment]
The LittleFS file system used in firmware 2.2.0 isn't efficient for a lot of small files. The issue is that each file takes a minimum of I think 8K space even if it has just 1 byte. So we implemented a feature that will delete some of the oldest log files if the flash space is getting too small.
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/master/main.cpp#L1617
