### ISSUE TITLE
GPIO station disabled on D1 Mini

### ISSUE THREAD

**Issue by agnoam** [OpenSprinkler/OpenSprinkler-Firmware#311]
I have built the firmware on D1 Mini using the provided `platformIO` configurations.
When I logged in to the UI, everything was working fine until I tried to set up a station over a specific `GPIO` pin.

How can I choose a specific GPIO?

**Comment by rayshobby** [comment]
This is because there are no free GPIO pins on the official OpenSprinkler 3.x hardware. All available GPIO pins on ESP8266 have been assigned to certain functions. The free pins are defined here:
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/master/defines.h#L360
if you are using your own hardware and there are any spare pins, you can add them to the list, they will show up on the UI. But you will need to also change the firmware to disable the functions of these pins. For example, if you don't use any sensors, the PIN_SENSOR1 and PIN_SENSOR2 can be released as free GPIO pins, but you need to define those pins as 255 so the firmware won't initialize those pins are sensor pins.

**Comment by iofirag** [comment]
> This is because there are no free GPIO pins on the official OpenSprinkler 3.x hardware. All available GPIO pins on ESP8266 have been assigned to certain functions. The free pins are defined here: https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/master/defines.h#L360 if you are using your own hardware and there are any spare pins, you can add them to the list, they will show up on the UI. But you will need to also change the firmware to disable the functions of these pins. For example, if you don't use any sensors, the PIN_SENSOR1 and PIN_SENSOR2 can be released as free GPIO pins, but you need to define those pins as 255 so the firmware won't initialize those pins as sensor pins.

" you can add them to the list"
is there an option to leave the sensor pins and add more pin variable to this list to handle my GPIO?

**Comment by rayshobby** [comment]
The PIN_FREE_LIST
I don't understand how you can use the same GPIO pin for multiple purposes? Are you asking how to use a pin both as a sensor pin as well as a free pin for GPIO station? That's not possible.

**Comment by agnoam** [comment]
@rayshobby, can you give me a reference to the place to disable the flow sensors for the `ESP8266`?

**Comment by rayshobby** [comment]
How many GPIO zones are you looking for? If you needs one, I suggest you start with the RFTX (radio-frequency transmitter) pin, assuming you are not using a RF transmitter:
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/master/defines.h#L418
change it to 255, so that effectively disables RFTX. That can free up pin 15, and you can add it to the PIN_FREE_LIST:
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/master/defines.h#L476
i.e. `#define PIN_FREE_LIST {15}`
This way GPIO 15 can be used for GPIO station.

**Comment by iofirag** [comment]
just for organize. and make it readable for future.

success build it for D1 mini board (8266 included)


changes:



in `defines.h` :

find this section:
`#elif defined(ESP8266) // for ESP8266`

disabled 2 sensors by set them as 255 (as you saied)
```
#define V0_PIN_SENSOR1       255 // sensor 1 disabled; GPIO12 is free
#define V0_PIN_SENSOR2       255 // sensor 2 disabled; GPIO13 is free
```

and add them to the free pin list:
`#define PIN_FREE_LIST     {12,13}`

then build.

build errors:

1. if you get build error on missing npm package `html-minifier-terser`:
just install it manual:
`npm i html-minifier-terser`

2. build error due to many cpp, .h missing files:
just build it again.

create pull request just for show the changes
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/pull/411

it is available in my repo:
https://github.com/aghaihome/D1-mini-Board-OpenSprinkler-Firmware/tree/master
