### ISSUE TITLE
RTC Local time when there isnt internet connection

### ISSUE THREAD

**Issue by iofirag** [OpenSprinkler/OpenSprinkler-Firmware#312]
Hi,
i have been install Opensprinkler on raspberry pi (`rpi3b+`) by pull this repo and run `./build.sh`,
and want Opensprinkler will use `RTC module` when there isnt internet connection
how can i achieve that? what model of RTC module is supported.

& by the way, 
i have future plans to move to `D1 mini` it will be possible also to run it with RTC module?

**Comment by rayshobby** [comment]
The microcontroller-based OpenSprinkler (i.e. OpenSprinkler 3.x) has built-in RTC which can maintain time when power is off. For RPi-based OpenSprinkler, because time keeping as well as NTP are managed by the Raspbian operating system, the firmware doesn't handle either of them. You can google 'rpi real-time clock' to install a RTC module yourself.

**Comment by iofirag** [comment]
Great. Thanks.
What about `d1 mini`?

**Comment by rayshobby** [comment]
If you have an RTC module connected to D1 mini (the RTC can be PCF8563 or DS1307, both very common and popular), then the firmware can auto-detect these and use them.

**Comment by iofirag** [comment]
thanks! :)
