### ISSUE TITLE
After update ...connection error!

### ISSUE THREAD

**Issue by looope** [OpenSprinkler/OpenSprinkler-Firmware#54]
Hi everybody!
I installed OSPI  with the sd card version.
I did not have any problems and I configured everything.

After trying to upgrade to 2.1.7 I can not connect to port 8080 (connection error), if I try to connect using port 80 I see the welcome page of ospi (OpenSprinkler Pi (OSPi) Pre-Configured SD Card,...etc).

Some suggestions
I have already tried several times to start from 2.1.4 of the SD card.

Thanks...

Red

**Comment by rayshobby** [comment]
Sorry about the issue. It turns out that the Raspbian version of the pre-configured SD card is out-dated and incompatible with the IPv6 feature in the latest OpenSprinkler firmware. So you should install the latest Raspbian from scratch and then install OSPi firmware by following the instructions. This should solve the problem for you.
