### ISSUE TITLE
Problems binding to 8080 

### ISSUE THREAD

**Issue by bikehead** [OpenSprinkler/OpenSprinkler-Firmware#56]
I have been running OSPI from a standard SD image for about 6 months.  Recently I did  a git pull and rebuilt the firmware.  It built fine but I lost my UI at 8080.  After some poking around I discovered that etherport.cpp is trying to use the IPV6 stack to open the port and this is failing.  I moved etherport.cpp one commit back and the UI returned.

So an upgrade to IPv6 on the standard SD image for OSPI doesn't work for me.

**Comment by 0-kaladin** [comment]
Weird same for me.  Thanks for the workaround.

**Comment by kpfleming** [comment]
This probably means that the kernel on the standard image doesn't have IPv6 enabled by default. It could be built as a module, or not available at all.

If you can ```modprobe ipv6``` successfully, then it's included as a module, and you'd only need to add ```ipv6``` to ```/etc/modules``` to have it loaded on each boot.

**Comment by pichirichi** [comment]
Same here, thanks for the workaround
> git checkout 8deb873 etherport.cpp
> sudo ./build.sh ospi
> sudo /etc/init.d/OpenSprinkler.sh restart

Worked like a charm

**Comment by zirkleta** [comment]
ipv6 to /ect/modules did not resolve for me.  The rolling up the previous etherport.cpp and rebuilding worked like a charm.

**Comment by rayshobby** [comment]
The pre-configured SD card image was build on a much older version of Raspbian and it doesn't support dual IPv4 and IPv6, while the latest firmware, in order to introduce support of IPv6, require that dual support. You should start with the latest Raspbian image and then install the firmware. That should solve the issue. We've now changed all instructions to retire the pre-configured SD card image.
