### ISSUE TITLE
Base version of `esp8266/Arduino` is old. Building against 2.5.2 results in `ar: file format not recognized`

### ISSUE THREAD

**Issue by hcooper** [OpenSprinkler/OpenSprinkler-Firmware#90]
There's some changes in more recent versions of `esp8266/Arduino` I'd like to have in OpenSprinkler.

Currently OpenSprinkler is built on `esp8266/Arduino` 2.4.1 (Mar 2018). The 2.5 branch was release Feb 2019, and 2.5.2 was release this month.

When I try to build OpenSprinkler following the [instructions here](https://openthings.freshdesk.com/support/solutions/articles/5000165132-how-to-compile-opensprinkler-firmware) against 2.5.2 the error I get is 

```
.../OpenSprinkler-Firmware-218$: make -f make.lin30
[...]
OLEDDisplayUi.cpp
RCSwitch.cpp
Creating core archive
../esp8266_2.4//tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-ar: /tmp/mainArduino/mainArduino_generic/ScheduledFunctions.cpp.o: file format not recognized
makeEspArduino.mk:244: recipe for target '/tmp/mainArduino/mainArduino_generic/arduino.ar' failed
make: *** [/tmp/mainArduino/mainArduino_generic/arduino.ar] Error 1
make: *** Waiting for unfinished jobs....
[...]
```

I've confirmed reverting `esp8266/Arduino` (and keeping all other dependencies up to date) results in a successful build. I'm a bit stuck getting past this.

**Comment by rayshobby** [comment]
I am pretty sure changing the ESP8266 core would require some source code changes because several classes have changed between 2.5.2 and 2.4.1, and none of the changes in 2.5.2 is essential to OpenSprinkler firmware. At this point, compiling with core 2.5.2 is not a very high priority, and when it comes to the time to update to 2.5.2, we need some long-term testing to make sure there are no issues. Will keep this in mind when we work on the next firmware.
