### ISSUE TITLE
Internet session required, opensprinkler domain required

### ISSUE THREAD

**Issue by RobotCaleb** [OpenSprinkler/OpenSprinkler-Firmware#92]
It would be nice if the web interface was self-contained. I was unable to access it when my internet was down earlier today as it couldn't load the UI from ui.opensprinkler.com

**Comment by rayshobby** [comment]
You can use OpenSprinkler mobile app, which has the required Javascripts built-in. We do not plan to embed the web interface on the controller, partly because the files are large, and partly because embedding it makes it harder to fix bugs as they come up (would require firmware update). If you want to access the controller without Internet, just download and use the OpenSprinkler mobile app.

**Comment by xaque208** [comment]
The app is quite good, also.
